---
- hosts: "{{host}}"
  gather_facts: no
  tasks:
    - name: test filecheck module 
      py_filecheck: filename=/etc/password
      become: yes
      become_user: root
      become_method: sudo
      register: output
    - name: debug vars
      debug: var=output
      
